Feature/notifications
Zelyder/Movie pull request #11
Opened 2021-02-15 10:03 UTC by Zelyder

2021-02-15 11:41 UTC, webanimal requested changes

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/core/Dialogs.kt
> +class Dialogs(val context: Context): DatePickerDialog.OnDateSetListener,
Убери сохранение контекста в конструкторе `Dialogs`, добавь `context` как параметр в публичные функции.

Сначала в классе описаны оверрайды родителя, потом публичные методы класса, потом оверрайды интерфейсов, потом приватные методы. Если про порядок публичных методов и оверрайды - это обсуждаемо, то приватные внизу это рекоммендуемо.

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/moviedetails/MoviesDetailsFragment.kt
> +    private val dialogs by lazy { Dialogs(requireContext()) }
Сначала см. коммент к классу `Dialogs`.

В каждом месте вызова, используй вызов функции из, например `dialogs.showCalendarPermissionDeniedDialog(context)`.

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/core/Notifications.kt
> +class AndroidNotifications(val context: Context) : Notifications {
Здесь тоже, не сохраняй контекст в классе.
Сделай notificationManager как lateinit var.
Передай контекст в initialize. И в публичные функции, где он нужен.

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/core/Notifications.kt
> +    override fun dismissNotification(movieId: Int) {
Здесь и в `dismissAllNotifications()` не получается использовать сохранённый манагер?

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/background/MyWorker.kt
> +            val notifications: Notifications = AndroidNotifications(context)
Вначале см. комменты в `Dialogs` и `AndroidNotifications`.

Судя по всему, тебе тут вообще инстанс этого класса не нужен.
Что тут получается: ты создаёшь класс и вызывается метод его конструктора.
Потом `init{}`, если есть.
Потом кастомный `initialize()`.
Потом `showNotification(movie)`.
По факту, тебе здесь надо только AndroidNotifications().show(movie). А уже внутри в приватных методах создавался бы манагер нотификаций, билдился билдер и показывалась бы нотификация.

Если бы в MainActivity не создавалась своя локальная копия, вообще все методы можно было бы перенести в `companion object`.

2021-02-15 11:41 UTC, webanimal commented on app/src/main/java/com/zelyder/movie/presentation/MainActivity.kt
> +    private val notifications: Notifications by lazy { AndroidNotifications(this) }
Сначала прочти комменты к `MyWorker.kt`.
У тебя здесь не вызывается `notifications.initialize()`.
После правок, надо убедиться, что здесь тоже создаётся `notification channel`.

2021-02-15 12:01 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/core/Notifications.kt
> +    override fun dismissNotification(movieId: Int) {
Ой, да что-то сглупил. )

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/core/Dialogs.kt
> +class Dialogs(val context: Context): DatePickerDialog.OnDateSetListener,
Поправил

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/moviedetails/MoviesDetailsFragment.kt
> +    private val dialogs by lazy { Dialogs(requireContext()) }
Поправил

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/core/Notifications.kt
> +class AndroidNotifications(val context: Context) : Notifications {
Поправил

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/core/Notifications.kt
> +    override fun dismissNotification(movieId: Int) {
Поправил

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/background/MyWorker.kt
> +            val notifications: Notifications = AndroidNotifications(context)
Поправил

2021-02-16 12:59 UTC, Zelyder commented on app/src/main/java/com/zelyder/movie/presentation/MainActivity.kt
> +    private val notifications: Notifications by lazy { AndroidNotifications(this) }
Поправил

2021-02-16 18:06 UTC, webanimal approved these changes

2021-02-16 18:45 UTC, merged